networks:
  workhub_network:
    driver: bridge

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/data
    restart: unless-stopped
    networks:
      - workhub_network

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: zookeeper
  #   environment:
  #     - ZOOKEEPER_CLIENT_PORT=2181
  #     - ZOOKEEPER_TICK_TIME=2000
  #   restart: unless-stopped
  #   networks:
  #     - workhub_network

  # kafka:
  #   image: confluentinc/cp-kafka
  #   container_name: kafka
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #   networks:
  #     - workhub_network
  #   depends_on:
  #     - zookeeper
  #   healthcheck:
  #     test:
  #       ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # kafka-setup:
  #   image: confluentinc/cp-kafka
  #   container_name: kafka-setup
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   networks:
  #     - workhub_network
  #   entrypoint: ["/bin/bash", "-c", "sleep 15 && /scripts/create-topics.sh"]
  #   volumes:
  #     - ./DockerConfig/InitKafka/create-topics.sh:/scripts/create-topics.sh

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - workhub_network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s
  
  kafka-topics-init:
    image: confluentinc/cp-kafka
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - workhub_network
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 10 &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic payment_cancellation --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic payment_intent_saving --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic employer_account_id_saving --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic freelancer_account_id_saving --partitions 1 --replication-factor 1 &&
        echo 'All topics created or already exist'
      "

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - workhub_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    restart: unless-stopped
    networks:
      - workhub_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    restart: unless-stopped
    networks:
      - workhub_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s


  postgres_identity:
    image: postgres:latest
    container_name: postgres_identity
    ports:
      - "5433:5432"
    volumes:
      - postgres_identity_data:/var/lib/postgresql
      - ./DockerConfig/InitPostgresIdentityDb:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: IdentityServiceDb
    restart: unless-stopped
    networks:
      - workhub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d IdentityServiceDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_projects:
    image: postgres:latest
    container_name: postgres_projects
    ports:
      - "5434:5432"
    volumes:
      - postgres_projects_data:/var/lib/postgresql
      - ./DockerConfig/InitPostgresProjectsDb:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: ProjectsServiceDb
    restart: unless-stopped
    networks:
      - workhub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ProjectsServiceDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_hangfire:
    image: postgres:latest
    container_name: postgres_hangfire
    ports:
      - "5435:5432"
    volumes:
      - postgres_hangfire_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: ProjectsServiceHangfireDb
    restart: unless-stopped
    networks:
      - workhub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ProjectsServiceHangfireDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  workhub_apigateway:
    build:
      context: .
      dockerfile: Backend/ApiGateway/Dockerfile
    container_name: workhub_apigateway
    ports:
      - "5000:5000"
      - "7000:7000"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network

  workhub_identityservice:
    build:
      context: .
      dockerfile: Backend/IdentityService/Dockerfile
    container_name: workhub_identityservice
    ports:
      - "5080:5080"
      - "7080:7080"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      postgres_identity:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-topics-init:
        condition: service_completed_successfully

  workhub_projectsservice:
    build:
      context: .
      dockerfile: Backend/ProjectsService/Dockerfile
    container_name: workhub_projectsservice
    ports:
      - "5081:5081"
      - "7081:7081"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      postgres_projects:
        condition: service_healthy
      postgres_hangfire:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-topics-init:
        condition: service_completed_successfully

  workhub_chatservice:
    build:
      context: .
      dockerfile: Backend/ChatService/Dockerfile
    container_name: workhub_chatservice
    ports:
      - "5082:5082"
      - "7082:7082"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      mongodb:
        condition: service_healthy
      kafka-topics-init:
        condition: service_completed_successfully

  workhub_paymentsservice:
    build:
      context: .
      dockerfile: Backend/PaymentsService/Dockerfile
    container_name: workhub_paymentsservice
    ports:
      - "5083:5083"
      - "7083:7083"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      kafka:
        condition: service_healthy
      kafka-topics-init:
        condition: service_completed_successfully

  workhub_frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: workhub_frontend
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      - workhub_apigateway

volumes:
  redis_data:
  azurite_data:
  mailhog_data:
  mongodb_data:
  postgres_identity_data:
  postgres_hangfire_data:
  postgres_projects_data:
